### ISSUE TITLE
System upgrades can't be disabled.

### ISSUE THREAD

**Issue by cschmidat** [pop-os/system-updater#14] opened 2022-05-05 23:14 UTC
Since updating Pop-OS to 22.04, I can't deactivate system updater anymore, which regularly messes up my system. I set auto-updates in gnome-control-center to off; here's the content of ~/.config/pop-system-updater/config.ron:
`(enabled:false,notification_frequency:Weekly)`.

Despite that, the service still runs (very aggressive) `apt-get -y --allow-downgrades full-upgrade` and `apt-get autoremove -y` commands.

I just disabled the com.system76.SystemUpdater.service unit in systemd -- I hope that is good enough.

**Comment by jacobgkau** [comment] 2022-05-05 23:19
`~/.config/pop-system-updater/config.ron` does not contain configuration for installing updates, that is only the configuration for notifications. The config for installing updates is at `/etc/pop-system-updater/config.ron`.

Can you please post the output of that global configuration file, along with `apt policy pop-system-updater` to confirm the version of it you have installed? This issue sounds like a duplicate of https://github.com/pop-os/system-updater/issues/11 and it was fixed with https://github.com/pop-os/system-updater/pull/13 just yesterday (we'll obviously want to investigate further if there's another case of it happening now.)

**Comment by jacobgkau** [comment] 2022-05-05 23:21
Notifications being disabled also suggests auto-updates are enabled (those two settings are always the opposite of each other with the way things work right now), so if you could provide a screenshot of your specific settings in the GUI, that might also help us replicate the issue.

**Comment by cschmidat** [comment] 2022-05-05 23:32
Oh I didn't see that it was probably just fixed -- sorry about that.

The file `/etc/pop-system-updater/config.ron` contains
`(auto_update:false,schedule:Some((interval:128,hour:22,minute:0)))(base)`. 

Here's the screenshot: ![Screenshot from 2022-05-05 16-30-34](https://user-images.githubusercontent.com/59363620/167043159-6ff9c20f-972d-4de0-9a16-687e9aed819e.png)

The version of pop-system-updater I'm running is `0.1.0~1651522263~22.04~6870527`. The auto-update to the new version failed due to dependencies I'll have to fix -- I'll upgrade to it, and I'll complain again if it's not working yet :smile:

**Comment by jacobgkau** [comment] 2022-05-05 23:35
> I'll upgrade to it, and I'll complain again if it's not working yet

Sounds good! Please let us know if it's still happening on the current version of system-updater, or close the issue if it's no longer happening. (It sounds like you know what's causing the dependency issue, but let us know if that's a Pop!_OS issue as well.)

**Closed as completed** 2022-05-15 17:43 UTC
